### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [1]:
### code here
import numpy as np
arr=np.array([[3,2,'nan',1],[10,12,10,9],[5,'nan',1,'nan']])
print("Original array:\n",arr)
a=np.where(arr=='nan',"True","False") 
print("Find the missing data of the said array:\n",a)

Original array:
 [['3' '2' 'nan' '1']
 ['10' '12' '10' '9']
 ['5' 'nan' '1' 'nan']]
Find the missing data of the said array:
 [['False' 'False' 'True' 'False']
 ['False' 'False' 'False' 'False']
 ['False' 'True' 'False' 'True']]


In [54]:
## sample output

##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [2]:
### code here 
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3])
a = np.array_equal(array1, array2)

# Print the result
print(a)  # prints True


True


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [3]:
## code here
import numpy as np

# original array
#array = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
array =np.arange(0,16).reshape(4,4)
print("Original array:\n",array)
print("\n New array after swapping first and last rows of the said array:\n" ,array[::-1])


Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 New array after swapping first and last rows of the said array:
 [[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [57]:
## sample output

###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [4]:
#### code here
lst=[1,2,3,4]
tpl=(5,6,7,9)
arr=np.array(lst)
arr1=np.array(tpl)
print(arr)
print(type(arr1))
arr1

[1 2 3 4]
<class 'numpy.ndarray'>


array([5, 6, 7, 9])

###### 5. Write a NumPy program to find common values between two arrays.

In [5]:
### code here
arr=np.array([1,2,3,4,5])
arr1=np.array([3,4,5,6,7])
comm=np.intersect1d(arr,arr1)
print("common values between two arrays:\n",comm)
comm1 = arr[np.isin(arr, arr1)]
print("common values between two arrays:\n",comm1)

common values between two arrays:
 [3 4 5]
common values between two arrays:
 [3 4 5]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [6]:
### code here
arr=np.array([[1,2,3,4,5,6]])
arr


array([[1, 2, 3, 4, 5, 6]])

In [7]:
arr1=np.reshape(arr,(3,2))
print("Reshape 3x2:\n",arr1)
arr2=np.reshape(arr,(2,3))
print("Reshape 2x3:\n",arr2)

Reshape 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
 [[1 2 3]
 [4 5 6]]


In [62]:
### sample output

###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [8]:
### code here
array = np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print("Original array:\n",array)
unique_values, counts = np.unique(array, return_counts=True)
print("Frequency of unique values of the said array:\n",unique_values,'\n',counts)  

result = np.stack((unique_values, counts), axis=1)
print("Result:\n",result)
result = np.vstack((unique_values, counts)).T
print("Result:\n", result)

Original array:
 [10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
 [10 20 30 40 50] 
 [3 4 2 2 1]
Result:
 [[10  3]
 [20  4]
 [30  2]
 [40  2]
 [50  1]]
Result:
 [[10  3]
 [20  4]
 [30  2]
 [40  2]
 [50  1]]


In [64]:
## sample output

###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [9]:
### code here
import numpy as np
array1=np.array([[0,0,0],[1,2,3],[4,5,6]])
array2=np.array([10,11,12])
print("Original arrays:\n","array1:","\n",array1,"\n","array2:","\n",array2)

print("\nNew Array:\n",np.add(array1,array2))
print("\nNew Array:\n",(array1+array2))

Original arrays:
 array1: 
 [[0 0 0]
 [1 2 3]
 [4 5 6]] 
 array2: 
 [10 11 12]

New Array:
 [[10 11 12]
 [11 13 15]
 [14 16 18]]

New Array:
 [[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [10]:
### code here
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [11]:
## code here
#arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
arr=np.arange(0,16).reshape(4,4)
print("Original array:\n",arr)
print("\nExtracted data: Third and fourth elements of the first and second rows:\n", arr[:2,2:])

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows:
 [[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [12]:
import numpy as np
now = np.datetime64('today', 'D')
yesterday = now - np.timedelta64(1, 'D')
tomorrow = now + np.timedelta64(1, 'D')
print("Yesterday:", yesterday)
print("Today:", now)
print("Tomorrow:", tomorrow)


Yesterday: 2023-01-18
Today: 2023-01-19
Tomorrow: 2023-01-20


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [ ]:
## sample output

First Monday in May 2017:
2017-05-01


In [13]:
import numpy as np
print("First Monday in May 2017:")
print(np.busday_offset('2017-05', 0,roll='forward',weekmask='Mon'))


First Monday in May 2017:
2017-05-01
